apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: resources 
  namespace: argocd 
spec: 
  destination: 
    namespace: app 
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: ./nginx-multiple-app/resources/
    repoURL: https://github.com/CostantinaC/gitops-certification-examples.git 
    targetRevision: HEAD
  syncPolicy: 
    automated: {}
